### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by seoker** [AtomLinter/linter-bootlint#16]
Hi, I just upgrade the package today, but Atom starts to complain the error as below.
Per checked, the `node` version on my machine is 5.1.0, this error continues if I upgrade it to 5.3.0.
Any idea about this? Is there any mistake on my environment? Thanks a lot.

![image](https://cloud.githubusercontent.com/assets/7975797/11986991/0c86375a-a98c-11e5-8ca2-2eb642c945f7.png)

**Comment by Arcanemagus** [comment]
Looks like you are on OS X, are you launching Atom from the GUI? For some bizarre reason Apple thought it would be a good idea to give them a completely blank environment.

If you launch Atom from a terminal do you still see this issue?

**Comment by seoker** [comment]
Oh yes, I l am on OS X and I launch Atom by spotlight (GUI).
Then I try to launch it by terminal, it works.

But now I am thinking about if this plugin really requires user to install `node` by himself?
Is it better that this plugin carry its standalone `node` or `bootlint`?
I'm not sure how other lint plugins would do..

Thanks for the quick reply :+1:

**Comment by Arcanemagus** [comment]
Currently at least this plugin is written to simply execute a `bootlint` installation on the machine, a prerequisite of which is having node installed.

It's possible to move over to the API for bootlint, which would mean we could run within Atom, but when re-writing this my primary goal was to just get this working for people. I would love to review a PR that moves this over to the API, especially since this plugin is still looking for an active maintainer.

Marking this as closed since it was an environment issue with OS X, feel free to keep commenting though :wink:.

**Comment by CoreySwish** [comment]
+1

**Comment by mdrmike** [comment]
+1  

I'm on Ubuntu and launching from zsh shell—needed to [install nodejs](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions)—missed that in prerequisites when I added the package.
